In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [2]:
from google.colab import files
uploaded = files.upload()

Saving WineQT.csv to WineQT.csv


In [3]:
df = pd.read_csv("WineQT.csv")
print(df.head())

   fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  Id  
0      9.4        5   0  
1      9.8        5   1  
2      9

In [4]:
print(df.tail())

      fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
1138            6.3             0.510         0.13             2.3      0.076   
1139            6.8             0.620         0.08             1.9      0.068   
1140            6.2             0.600         0.08             2.0      0.090   
1141            5.9             0.550         0.10             2.2      0.062   
1142            5.9             0.645         0.12             2.0      0.075   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
1138                 29.0                  40.0  0.99574  3.42       0.75   
1139                 28.0                  38.0  0.99651  3.42       0.82   
1140                 32.0                  44.0  0.99490  3.45       0.58   
1141                 39.0                  51.0  0.99512  3.52       0.76   
1142                 32.0                  44.0  0.99547  3.57       0.71   

      alcohol  quality    Id  
1138     11.0      

In [5]:
df.shape

(1143, 13)

In [15]:
df = np.array(df)
X = df[:,:-1]
Y = df[:, 1]
print(df)

[[7.400e+00 7.000e-01 0.000e+00 ... 9.400e+00 5.000e+00 0.000e+00]
 [7.800e+00 8.800e-01 0.000e+00 ... 9.800e+00 5.000e+00 1.000e+00]
 [7.800e+00 7.600e-01 4.000e-02 ... 9.800e+00 5.000e+00 2.000e+00]
 ...
 [6.200e+00 6.000e-01 8.000e-02 ... 1.050e+01 5.000e+00 1.594e+03]
 [5.900e+00 5.500e-01 1.000e-01 ... 1.120e+01 6.000e+00 1.595e+03]
 [5.900e+00 6.450e-01 1.200e-01 ... 1.020e+01 5.000e+00 1.597e+03]]


In [21]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2)
print(X_train[:4])
print(X_train.dtype)
Y_train_class = np.digitize(Y_train, bins=np.linspace(min(Y_train), max(Y_train), num=4))
print(Y_train_class.dtype)

[[7.7000e+00 4.9000e-01 2.6000e-01 1.9000e+00 6.2000e-02 9.0000e+00
  3.1000e+01 9.9660e-01 3.3900e+00 6.4000e-01 9.6000e+00 5.0000e+00]
 [7.0000e+00 4.9000e-01 4.9000e-01 5.6000e+00 6.0000e-02 2.6000e+01
  1.2100e+02 9.9740e-01 3.3400e+00 7.6000e-01 1.0500e+01 5.0000e+00]
 [7.8000e+00 6.4500e-01 0.0000e+00 2.0000e+00 8.2000e-02 8.0000e+00
  1.6000e+01 9.9640e-01 3.3800e+00 5.9000e-01 9.8000e+00 6.0000e+00]
 [6.7000e+00 6.7000e-01 2.0000e-02 1.9000e+00 6.1000e-02 2.6000e+01
  4.2000e+01 9.9489e-01 3.3900e+00 8.2000e-01 1.0900e+01 6.0000e+00]]
float64
int64


In [22]:
clf = KNeighborsClassifier()
clf.fit(X_train,Y_train_class)

KNeighborsClassifier()

In [23]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
le.fit(np.concatenate((Y_train, Y_test)))
Y_train_encoded = le.transform(Y_train)
Y_test_encoded = le.transform(Y_test)
clf = KNeighborsClassifier()
clf.fit(X_train, Y_train_encoded)

KNeighborsClassifier()

In [26]:
score = clf.score(X_train,Y_train_class)
sample_data_point = [[10, 15, 0, 0, 0, 9, 0, 8, 0, 6, 0, 2]]
print(clf.predict(sample_data_point))

[48]


In [27]:
predict = clf.predict(X_test)
print(accuracy_score(Y_test_encoded, predict))

0.08296943231441048
